/**
 * Export data to CSV format and trigger download
 */
export function exportToCSV(data: Record<string, unknown>[], filename: string): void {
    if (!data.length) return
    
    const headers = Object.keys(data[0])
    const csvContent = [
        headers.join(','),
        ...data.map(row => 
            headers.map(h => {
                const val = String(row[h] ?? '')
                // Escape commas and quotes
                return val.includes(',') || val.includes('"') || val.includes('\n')
                    ? `"${val.replace(/"/g, '""')}"` 
                    : val
            }).join(',')
        )
    ].join('\n')
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${filename}_${new Date().toISOString().split('T')[0]}.csv`
    link.click()
    URL.revokeObjectURL(url)
}

/**
 * Export data to JSON format and trigger download
 */
export function exportToJSON(data: unknown, filename: string): void {
    const jsonContent = JSON.stringify(data, null, 2)
    const blob = new Blob([jsonContent], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${filename}_${new Date().toISOString().split('T')[0]}.json`
    link.click()
    URL.revokeObjectURL(url)
}

/**
 * Print-friendly view of current page
 */
export function printReport(title: string): void {
    const printWindow = window.open('', '_blank')
    if (!printWindow) return
    
    printWindow.document.write(`
        <html><head><title>${title} - Apex Health</title>
        <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; color: #1e293b; }
            h1 { font-size: 24px; margin-bottom: 8px; }
            .subtitle { color: #64748b; margin-bottom: 24px; }
            table { width: 100%; border-collapse: collapse; margin-top: 16px; }
            th, td { padding: 8px 12px; border: 1px solid #e2e8f0; text-align: left; }
            th { background: #f8fafc; font-weight: 600; }
            .generated { color: #94a3b8; font-size: 12px; margin-top: 24px; }
        </style></head>
        <body><h1>${title}</h1>
        <p class="subtitle">Generated by Apex Health Intelligence</p>
        <p class="generated">Report generated: ${new Date().toLocaleString()}</p>
        </body></html>
    `)
    printWindow.document.close()
    printWindow.print()
}
